version: "3.9"

services:
  api:
    build:
      context: ./api
    container_name: geo-api
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:8080/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    build:
      context: ./frontend
    container_name: geo-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE=http://localhost:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      api:
        condition: service_healthy
    command: npm run dev

networks:
  default:
    name: geo-net
