name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies (frontend)
        working-directory: ./frontend
        run: npm ci

      - name: Lint (optional)
        working-directory: ./frontend
        run: npm run lint || echo "no lint script"

      - name: Build (frontend)
        working-directory: ./frontend
        run: npm run build

      - name: Test (frontend)
        working-directory: ./frontend
        run: npm test --if-present
